name: OFYP-main
channels:
  - conda-forge
dependencies:
  - python=3.11.8
  - numpy
  - pandas
  - pip
  - yaml
  - matplotlib
  - seaborn
  - jupyter
  - ipykernel # required for jupyter notebook in VS Code
  - scikit-learn=1.5.0
  - pymatgen=2024.6.10
  # - matminer=0.9.2
  - openpyxl
  - requests
